version: '3'
services:
  db:
    image: postgres:15.4-alpine
    container_name: go-oapi-sample-db
    environment:
      POSTGRES_USER: conduit_user
      POSTGRES_PASSWORD: password
    ports: ['5432:5432']
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
